// Loading
export const LOAD_RESULTS_START = 'LOAD_RESULTS_START';
export const LOAD_RESULTS_SUCCESS = 'LOAD_RESULTS_SUCCESS';
export const LOAD_RESULTS_FAIL = 'LOAD_RESULTS_FAIL';

export const LOAD_RECIPE_START = 'LOAD_RECIPE_START';
export const LOAD_RECIPE_SUCCESS = 'LOAD_RECIPE_SUCCESS';
export const LOAD_RECIPE_FAIL = 'LOAD_RECIPE_FAIL';

//  Search Results
export const SET_RESULTS = 'SET_RESULTS';

// Recipe
export const SET_RECIPE = 'SET_RECIPE';

// Servings
export const SET_SERVINGS = 'SET_SERVINGS';
export const MODIFY_SERVINGS = 'MODIFY_SERVINGS';

// favorites
export const MODIFY_FAVORITE = 'MODIFY_FAVORITE';
export const SET_FAVORITES = 'SE_FAVORITES';

// Shopping List
export const ADD_TO_SHOPPINGLIST = 'ADD_TO_SHOPPINGLIST';
export const REMOVE_FROM_SHOPPINGLIST = 'REMOVE_FROM_SHOPPINGLIST';
export const MODIFY_WITHIN_SHOPPINGLIST = 'MODIFY_WITHIN_SHOPPINGLIST';
export const SET_SHOPPINGLIST = 'SET_SHOPPINGLIST';
